### ISSUE TITLE
ENH: add a setting to bind `esc` to `leave-current-mode`

### ISSUE THREAD

**Issue by ianhi** [jupyterlab-contrib/jupyterlab-vim#101]
We should add a setting that allows binding `Esc` to `leave-current-mode` as proposed in #70

**Comment by firai** [comment]
It seems like the search box <kbd>Esc</kbd> binding for JL 4.0.x that was added in #90 needs to be disabled in order for double duty <kbd>Esc</kbd> à la #70 to work. (The `leave-insert-mode` rule also needs to be disabled if this is added as a user preference and if one starts from the auto-generated shortcut bindings rather than blank settings. Obviously this would be done if it was done from the extension itself.) As far as I can tell, closing the search box by <kbd>Esc</kbd> still seems to work in notebooks without the extra search box binding, at least in JL 4.0.3.

```json
        {
            "args": {},
            "command": "documentsearch:end",
            "keys": [
                "Escape"
            ],
            "selector": ".jp-mod-searchable .jp-Notebook .cm-vimMode",
            "disabled": true
        },
        {
            "args": {},
            "command": "vim:leave-current-mode",
            "keys": [
                "Escape"
            ],
            "selector": ".jp-NotebookPanel[data-jp-vim-mode='true'] .jp-Notebook.jp-mod-editMode"
        }
```

**Comment by firai** [comment]
A proposed implementation has been opened at #110
