### ISSUE TITLE
Version support policy

### ISSUE THREAD

**Issue by firai** [jupyterlab-contrib/jupyterlab-vim#115]
Is there a policy regarding which jupyterlab-vim/JupyterLab versions we're "supporting", either within the repo or within the organization? I understand that JL itself has a policy of maintaining the two latest major versions, but this repo doesn't seem to be keeping any branches for maintenance of jupyterlab-vim 0.x for JL 3.x.

I'm asking this partly in reference to #71, which seems to be resolved if we're only maintaining 4.x. On the other hand, if we're planning to accept PRs for JL 3.x users, it seems like we should split off a 0.x branch. Since the number of JL 3.x users may still be substantial for some time, this may come up for other issues as well.

@ianhi @krassowski

**Comment by krassowski** [comment]
I think there is no policy as of now (happy to be corrected though!).

With other extensions in the past my approach was "support the previous major version of JupyterLab as long as it is being developed", this is once we transitioned to JupyterLab 3.0 I would still fix issues for JupyterLab 2-compatible version for as long as there were minor releases (e.g. JupyterLab 2.3) and otherwise only backport security fixes. But it is not clear if there will be JupyterLab 3.7.

If you are asking if it is fine to close the issue my answer would be yes. If you are asking is someone is going to help with a release if you yourself need to support older version the answer is likely yes. If you are asking if other maintainers are going to actively fix bugs in older versions the answer is likely no.

**Comment by firai** [comment]
Thanks for your response, @krassowski! It sounds like we can basically say that issues that exist exclusively in 0.x will be "won't fix" then, unless another contributor comes along to maintain that version.

**Comment by firai** [comment]
Closing as I believe we're in agreement here
