### ISSUE TITLE
for now version date 2024.07.03 ,I want to uninstall this -vim plug ,but can't success ,why?

### ISSUE THREAD

**Issue by woodgreat** [jupyterlab-contrib/jupyterlab-vim#142]
for now version date 2024.07.03 ,I want to uninstall this -vim plug ,but can't success ,why?

I clicked times of button in jupyterlab left bar
------------------------------------------------------------------------------------
[axlair-jupyterlab-vim](https://github.com/jupyterlab-contrib/jupyterlab-vim)
4.1.3
Code cell vim bindings
Uninstall
  Disable
------------------------------------------------------------------------------------

both "Uninstall" and "Disable" button can't work ,why?
how to remove this plug? 
thanks

**Comment by firai** [comment]
Why the Extension Manager can't uninstall or disable the plugin might have to do with the fact that the plugin isn't simple, and it's probably not something that can be controlled at the plugin level.

The recommended way to uninstall would be to follow https://github.com/jupyterlab-contrib/jupyterlab-vim?tab=readme-ov-file#uninstall at the terminal/command prompt.

If you aren't able to uninstall because you're using an installation provided by someone else, you can disable the plugin by going to `Settings` menu → `Settings Editor` → `Notebook Vim` → Uncheck both `Enabled` and `Enabled in Text Editor`.

**Comment by woodgreat** [comment]
> Why the Extension Manager can't uninstall or disable the plugin might have to do with the fact that the plugin isn't simple, and it's probably not something that can be controlled at the plugin level.
> 
> The recommended way to uninstall would be to follow https://github.com/jupyterlab-contrib/jupyterlab-vim?tab=readme-ov-file#uninstall at the terminal/command prompt.
> 
> If you aren't able to uninstall because you're using an installation provided by someone else, you can disable the plugin by going to `Settings` menu → `Settings Editor` → `Notebook Vim` → Uncheck both `Enabled` and `Enabled in Text Editor`.

that's true.

now ,I disabled it before hjkl > ijkl control cursor came , I am not remove the plugin anyways, a wait that ,
thank you
